### ISSUE TITLE
Problems with quaterly data

### ISSUE THREAD

**Issue by EduardoClark** [alexkowa/x12#2]
I can't seem to get quaterly data to work with this packages. For example this works

```
xts <- x12(AirPassengers)

```

and this doesn't work

```
tmp <- ts(AirPassengers, frequency=4)
xts <- x12(tmp)

```

where I get the following output:

X-13ARIMA-SEATS Seasonal Adjustment Program
 Version Number 1.0 Build 150
 Execution began  Nov 25, 2013  14.35.56 

  Reading input spec file from Rout.spc
  Storing any program output into Rout.out
  Storing any program error messages into Rout.err
  Storing any diagnostics output into gra/Rout.udg

 Execution complete for Rout.spc at  Nov 25, 2013  14.35.57 
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'gra/Rout.NA': No such file or directory

**Comment by wzrzt** [comment]
Platform:windows10_64bit
First , I put the folder 'winx12' in c:\program files\, and it output errors such as "can not find  Rout.err", "Can not find air.err"  and so on .
I realized that it may be caused by authority problem, So I decided to move the folder to somewhere authority requests less.
When I move the folder 'winx12' to paritition D, the error disapear, and the output is normal.

**Comment by jbbinder8** [comment]
I had the same problem: 

> Error in file(file, "rt") : cannot open the connection

when running quarterly data with x13as.exe. For monthly I get no errors.

The workarounds above didn't solve the problem. I switched to x12a.exe and it's working.
